### ISSUE TITLE
Cannot edit multiple datatables: duplicated onEditRow callbacks

### ISSUE THREAD

**Issue by MaDooSan** [KasperOlesen/DataTable-AltEditor#18] opened 2018-12-07 21:08 UTC
(This issue may have been briefly mentioned in the to-do)

Editing multiple datatables seems to faulty since the onEditRow callback occurs for every datatable in the DOM while it should only be called for the selected element. While the selected row is still updated, other entities are also overwritten unless additional custom validation is added.

Following error is raised for the datatables that unintentionally call onEditRow:

Uncaught TypeError: Cannot set property '_aData' of undefined
    at _Api.<anonymous> (jquery.dataTables.js:8030)
    at _Api.data (jquery.dataTables.js:7105)
    at altEditor._editRowCallback (dataTables.altEditor.free.js:699)
    at Object.success (dataTables.altEditor.free.js:393)
    at fire (jquery-1.12.4.js:3232)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.js:3362)
    at done (jquery-1.12.4.js:9840)
    at XMLHttpRequest.callback (jquery-1.12.4.js:10311)

**Comment by karthiksd9** [comment] 2019-01-11 14:31
I have tried with 2 datatables on a single page. its not working properly.
Its opening 2 add row popup when clicked on add row of first table.
on save nothing is added to table.

**Comment by luca-vercelli** [comment] 2019-01-15 11:20
I think the problem is that there are two buttons with the same id on the same page

probably we should concatenate the id of the button with the id of the datatable

see https://github.com/KasperOlesen/DataTable-AltEditor/blob/9716fe0ba215c4b39e18e1c3f8b086f16d457c07/src/dataTables.altEditor.free.js#L198

**Comment by luca-vercelli** [comment] 2019-01-24 23:02
This should be fixed now. Can anybody try and give me some feedback?

**Comment by morehek** [comment] 2019-02-06 15:42
You can first remove event handler in _setup function if it exists.

Put line:
$(document).off('click', '#addRowBtn');
Before line:
$(document).on('click', '#addRowBtn', function (e) {

Repeat same for #deleteRowBtn and #editRowBtn

**Comment by luca-vercelli** [comment] 2019-02-06 21:44
@morehek, I don't think so. The point is that we need one different callback function per each datatable on the web page. `$(document).off('click', '#addRowBtn');` would disable the callbacks previously defined.
Instead, I have changed $(document) with $(self.modal_selector) in order to link each handler with the correct datatable.

**Closed** 2019-03-11 10:36 UTC
Labels: enhancement
